Adding Github Actions Pipeline 8

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -28,4 +28,4 @@ jobs:
       run: npm run dev
 
     - name: Stop application
-      run: kill $(lsof -t -i:3000) || echo "Process not found"
+      run: kill $(lsof -t -i:8080) || echo "Process not found"
